language: python
sudo: false
python:
- '2.7'
- '3.3'
- '3.4'
env:
- DJANGO_VERSION="Django>=1.7,<1.8"
- DJANGO_VERSION="Django>=1.8,<1.9"
  global:
    - secure: orS6GrKWFvXDAVoLfmdaNpvO91UHUWjvYQQFw8fJcTJuFmEOqCQWUr+5MaG+0nR9i5H7fFmRWqSKXcsoew71bv/ZejDgVGzbtw4L3n++EUaVrZIoBztn1NgoeQp6kR+Pw1HQTSjy91N4SzXljvwOWapj68Nj2MkT4txeDRC/cxZMyUPXzDBtkfJ3q7YHJupBz7ZVq8cBU4bM8Rpkk4c+FKQ7aj9LFoRthNt3sBLFo7WYvVEWpj8DAlNymuIN06XJcj6PhRWeSEQaQvfPwdJ20clPSV420syyE3ZSkp+A4/Jll75XWITfSCEfLCWfFsBRi/g40lDR3GqReGZ2uB0wmQMetPEwYq8oom323NHvGGyWnW1cGEqn+iQxNBEyyHbjvcXZOlyY0pucHOhs/frtceTE9XNuLlC0FlP5hHRD9LgWyJ6yahxBjOY0JE4YbWS856/O6Z2scnPMKJy4ZRf7GTA9HheEPEgqtKg/vEbHARlSJZiIbByjbJi7xqRGqavPY1ZJQYnr14zwM5RIDbX1Ms7XkFhNR4M/A7g2DAuSXqvU3llX7istzOmmBgPx57DOuag3KGjWXdcLFf0a+Wja1PSrLnl+Mu0J0zVUOGa5wQzcQCsQSnOlQk7Dg7PLNBwQGjVJd1IxMyowmwIphRjjbuHFHlU0O9SRD7fYbocnl2s=
    - secure: GnEzaDYg7j7EnpIXIzAEL0ju4DwBAHMsZdsMmyUcgFF7ReKJM+MLiqHFXlAV7EHv3Yu6p1sSYHDNqOA29rbOBtqhHAR3Ao2BgXxxQgSoO5i2GLV9fOLOtm+TAVon+bZKALe7weSrudz6W3k/ISO0WjfULqeIbQDqafrNfCTmTkgVmV7bepCBJk/fdWq9YRnm1vXR7N4GfgL14YLU268IfNZ2UKmNBsgZ0XoyhDqF8W1sIzYaCQLnJXHQJnB4XSFR72gHtG/Tdxn5daOgSSVynF+ioioErUCW5IAGkPpic02gm2u/DtJsNtPIRxzs5Hi1KqHSSloLYlwN3/A8J+/o/D7lhIVHfywcSBYLOWQZL5pF2XtSC+1ff5KxLs0veE7kUq5cINFT23yyIQzgJ5n0HSk7zBzKI4uASTtWn1jy/nDkjqxD1FfuA2igNF4pYl8ERGFwuAJGplkz4Rpy5lQnmOsKd6alBMQ1nlMxGOE3CVb9TJA0BG44/JSZB2trUTZ/yHf5SmSjGvINdxaeVU/qIck5O1VTa8d965Ihr4lxWCHdnp4MHPXVL9+bOG5xhi2eTzMXQSwqu8ljh1WtoIwRRcEZ1kt70BY4PF0t4OQOZRrydbtgBkSqz7lJIRUXjtU2rUP70SdSbgYk3lfOo7FogBJbtPawHpZCRTle93bPf3k=

install:
- pip install pip -U
- pip install codecov
- pip install -r requirements.txt
- pip install "$DJANGO_VERSION" -U
script:
- coverage run --source='star_ratings' runtests.py
- cd demo; python manage.py test
after_success:
- codecov
notifications:
  slack:
    secure: MlrEVotOd2wuf+mgur/ISn/bC41Abqk7YXA7887DBqESERjO7yLtvNbOTcaxXzj2tCW7cpUOjo7dcnU8Hvo9sCWYM9IIDdwlAg2REq/SN7j9JGdb0cl5Wzk5rH19muY8b93bCvQIRkoMvrnvqCve58o7LKrUsMhItiAUeFiVrq/u5LqtNjPNzVIEpfkIJzXFXMVMGHX8m8/IJmCA+gMNIC7R9zTEW72FmcAFBp/JfhGhuIW+vn3Vh8/8HHolu5xjtcf0e6WGijBhYyYtM51RT8eZbgoY5VyUD5XgsPX6CIwQy/cXUChsW+LQN9F10v1T2hKnPoLM+ytyI0p6pAGQeEUkFKRnqSXCBJQ1aQaPGVFpBmP45TEJlJmvb7BwLrJFWKb+Lu0eemza0tkXg8ULSiXxpDinJwLql2mQ6JP+4acsW8gXToBATjqXLpiYzuGLpAOCgDHHwirpRJ85m1KlbIQf8kdgyprRNMEdIzRW2chjvWgcpp/23Lqkbro+M/vjp0UtI8fr3aMFiW1JTiwA5MVQN1jqcW/qspK3jSKOg5AnYpKzcM6nMs9h6YgYWWAvaKiOh7puL2tV+5+8OJkoosj4a5lTNR+/M//GSSvPmpb+niu+vbXGq/2A82hK+v1dOLbEUgW2LaQua/Z7XsR0c0PCe7zXVihG50JW47Agywg=
addons:
  sauce_connect: true