language: python
sudo: false
python:
- '2.7'
- '3.3'
- '3.4'
env:
  matrix:
  - DJANGO_VERSION="Django>=1.7,<1.8"
  - DJANGO_VERSION="Django>=1.8,<1.9"
install:
- pip install pip -U
- pip install codecov
- pip install -r requirements.txt
- pip install "$DJANGO_VERSION" -U
script:
- coverage run --source='star_ratings' runtests.py
- cd demo; python manage.py test
after_success:
- codecov
notifications:
  slack:
    secure: MlrEVotOd2wuf+mgur/ISn/bC41Abqk7YXA7887DBqESERjO7yLtvNbOTcaxXzj2tCW7cpUOjo7dcnU8Hvo9sCWYM9IIDdwlAg2REq/SN7j9JGdb0cl5Wzk5rH19muY8b93bCvQIRkoMvrnvqCve58o7LKrUsMhItiAUeFiVrq/u5LqtNjPNzVIEpfkIJzXFXMVMGHX8m8/IJmCA+gMNIC7R9zTEW72FmcAFBp/JfhGhuIW+vn3Vh8/8HHolu5xjtcf0e6WGijBhYyYtM51RT8eZbgoY5VyUD5XgsPX6CIwQy/cXUChsW+LQN9F10v1T2hKnPoLM+ytyI0p6pAGQeEUkFKRnqSXCBJQ1aQaPGVFpBmP45TEJlJmvb7BwLrJFWKb+Lu0eemza0tkXg8ULSiXxpDinJwLql2mQ6JP+4acsW8gXToBATjqXLpiYzuGLpAOCgDHHwirpRJ85m1KlbIQf8kdgyprRNMEdIzRW2chjvWgcpp/23Lqkbro+M/vjp0UtI8fr3aMFiW1JTiwA5MVQN1jqcW/qspK3jSKOg5AnYpKzcM6nMs9h6YgYWWAvaKiOh7puL2tV+5+8OJkoosj4a5lTNR+/M//GSSvPmpb+niu+vbXGq/2A82hK+v1dOLbEUgW2LaQua/Z7XsR0c0PCe7zXVihG50JW47Agywg=
addons:
  sauce_connect:
    username: 'django-star-ratings'
    access_key:
      secure: o9illUJKqoFj+wPEYCkliyIq0jSWiEGjKys6FfD8qmSNwy7gQ6z8oxFwq0CGPROn3aeSJ/tkjSEqQ9pI9RevfhaRoShYImPzvLmRboikzFpLpEVDLJW69im1ZNpQ4P2NUZNx+gQRW3d+Ebh9EbXhyhCPR+ug+jXmJZz/fWRAb/AJiiqiuzgdH82ZwkIgNR8Hfck9UXsvD4hHgbQnEtsAhRwqUcizh+47/xHzCqbCcXZdCSUAsdZ3lVimIsIONZEtCctJ2K7F9MkMgAHGHvblEgFD4TH8kgJXEEcztlt3PipmTlB6YXObxApnYURry9Pr2FU8jzgfIbvhnBgjzpGObXV5H2PYoHl8mnJzjs3OQphpYh4PBpP8rdg5NaR/Dx9w4guCMtnqLA/sL0CbUGek4Pl7dwyXGCV7OXPX7FYqQWoIfROZn7bYbqnJlwVb1pEWZhILVIfE1o/8JtlOlzUzqdCgxGelhFzCN/9BVOUqyhcLYC9iKOnHPudryqeJwans1KUrJkJQzWbcqBqV7mKflpKbRmLLoVgu1eIIeUj7j4225yrfRwEP4z58LWWXMZNzuZ+EsVujhZ1II7sT2vUCAMMcPnfluWkwHsr6LWaqggm91G2dsPLA3XXSB1JbiWGYo9uPfzAromUXoxnIzUZx9gpR1+e121pmpNJ+AM+AjLQ=
