language: python

sudo: false

before_install:
  - pip install codecov

python:
  - "2.7"
  - "3.4"

install:
  - pip install tox

script:
  - coverage run --source='star_ratings' runtests.py

after_success:
  - codecov