language: python
sudo: false
python:
- '2.7'
- '3.3'
- '3.4'
env:
- DJANGO_VERSION="Django>=1.7,<1.8"
- DJANGO_VERSION="Django>=1.8,<1.9"
global:
  - secure: ljZ+TXyl+0XQkhN/iK1w18CQjRHFA4xkF1+x74Veh6/Drl+pcJljYVtCQHSMWymsQ+dMK7PdAeBcICkYsJwBWC3ar581Ezcl7tHM3nDxZ6D1JMU0TJvMRzBE9Go89vo9SextZiD5Sww/utsM09JCQ9IhLLnKMO6B3FdxHnpedZ6XQ3ewukXGwSZWkATQyIQKE0E7CGILKq9KBhIAKXksHWo6YYEwHz2nDhiAqz2s4izpb8nYaipF2jrgj37CXKax+XncWekzkRqPWRJ6XORZF/wCm3eFvPDConwfjleJi9IA8PQnmZlXuidw1JKSEj4RQe2vzzTpSraF5iZ516PcMpFc7VQiL1031jkY2DpE8Rmg6h6mTGRoXc1ZyTuZxOGgUo+fCnzLm0bKD5jLpdLcfhoDZB6ed78iH6idm9m4yRJEUQRpnRuL3/qsx5+XzlfE/wI6vUJ1t13b+07VD62KDr4kf8ZIAekGzD13A2D95+wil/v1iRuWOASnlfUJjRWUCQkevH8D0iwK7YpOKIYUEBmWaecBcKCmc2+iEipDYVuZNlrSMUuXDts1YFC6Q9qYRJ+CbVqV9nnVj+tXf+1r8zj7Tkl/D4o9le54y6m4/qY4E83SsAlddGukfvo3CaFutjCL3UTjTRJkDJIPo9zXis2xy1r3Ub1NDEjJtkLMbC0=
  - secure: ZOCU9i9RaBfDtrvykJfoz/U5wd4LILo71/k3l81CyiaWCbQMP376wGJ69A3TwILn3uM987mAvUbKtG52SdJpNse9Fjlnd1dgVHWnGTMHvgIl7CQSl1it+fi4fjXOM5T+YFgSRCmp+ffdgitEPBP8298FU/ERQ9B71AGoOr2NvRFMK5QCdl016x+3hQXQ2GuvRDtquzvUSmm2CaWQhcU7lw3rDx2XyMNWz+UkWxY1julyU3F1jHNtxJbl/VBplUOkoV8r5+BTX0KycNLWwCxXtc9mI0JBBq60N9Y2gDk5ovIvZYMM3A189dUDTCthpdRhK8UXDQFTHbnkmywT3qepkV+hUcOQfBgn7VR2/uAHhHqYYFwsuG+L38zO+t82nr1DR2dlvzZMeCnvedci4O69KHR4vxvEAZzusPm+P8PhUP05/iW5xIlnSOqDZ3UYH3Y2xkjfWc7/u75CdsFHL/mXZRYxo45SIIcfMYWefpnasOyLt+7cYvAcGyvXGrMaiBb2jcePdBjcsuKAsxHYYZbIJFNsCfMbmonJwvX/e/CHyfqNUkDO8xnfb+vg1X4TBss1hkqB/LyMqRyh6PZuSE1xAyiza7lzmagkwTcJVXl0+o1+2VOF+8UpYhIiWr9xo15+WOtZU0heb72Y/ZoHnNwvB9gCvmCsAMURlZgDxxe02TI=
install:
- pip install pip -U
- pip install codecov
- pip install -r requirements.txt
- pip install "$DJANGO_VERSION" -U
script:
- coverage run --source='star_ratings' runtests.py
- cd demo; python manage.py test
after_success:
- codecov
notifications:
  slack:
    secure: MlrEVotOd2wuf+mgur/ISn/bC41Abqk7YXA7887DBqESERjO7yLtvNbOTcaxXzj2tCW7cpUOjo7dcnU8Hvo9sCWYM9IIDdwlAg2REq/SN7j9JGdb0cl5Wzk5rH19muY8b93bCvQIRkoMvrnvqCve58o7LKrUsMhItiAUeFiVrq/u5LqtNjPNzVIEpfkIJzXFXMVMGHX8m8/IJmCA+gMNIC7R9zTEW72FmcAFBp/JfhGhuIW+vn3Vh8/8HHolu5xjtcf0e6WGijBhYyYtM51RT8eZbgoY5VyUD5XgsPX6CIwQy/cXUChsW+LQN9F10v1T2hKnPoLM+ytyI0p6pAGQeEUkFKRnqSXCBJQ1aQaPGVFpBmP45TEJlJmvb7BwLrJFWKb+Lu0eemza0tkXg8ULSiXxpDinJwLql2mQ6JP+4acsW8gXToBATjqXLpiYzuGLpAOCgDHHwirpRJ85m1KlbIQf8kdgyprRNMEdIzRW2chjvWgcpp/23Lqkbro+M/vjp0UtI8fr3aMFiW1JTiwA5MVQN1jqcW/qspK3jSKOg5AnYpKzcM6nMs9h6YgYWWAvaKiOh7puL2tV+5+8OJkoosj4a5lTNR+/M//GSSvPmpb+niu+vbXGq/2A82hK+v1dOLbEUgW2LaQua/Z7XsR0c0PCe7zXVihG50JW47Agywg=
addons:
  sauce_connect: true